#!/bin/bash

#First copy the files into /var_html
rsync -auv --chown=1000:1000 /var/www/html /

#Then sync repeatidly
while :
do
    rsync -auv --chown=www-data:www-data /html /var/www
    sleep 1
done

